package turn

import (
	"encoding/json"
	"strings"
	"testing"
	"time"

	"github.com/dontfeedthecode/ccxray/internal/record"
)

// replay feeds inline JSONL through a fresh Builder.
func replay(t *testing.T, lines string) *Builder {
	t.Helper()
	b := New()
	for _, l := range strings.Split(strings.TrimSpace(lines), "\n") {
		if l = strings.TrimSpace(l); l == "" {
			continue
		}
		var r record.Record
		if err := json.Unmarshal([]byte(l), &r); err != nil {
			t.Fatalf("fixture line: %v\n%s", err, l)
		}
		b.Add(r)
	}
	return b
}

// The record order Claude Code writes around a /compact. Every identifier and
// every line of prose here is invented.
const compactSequence = `
{"type":"user","uuid":"u1","timestamp":"2026-01-02T10:00:00.000Z","message":{"role":"user","content":"tidy up the parser"}}
{"type":"assistant","uuid":"a1","requestId":"r1","timestamp":"2026-01-02T10:00:04.000Z","effort":"high","message":{"model":"claude-opus-5","stop_reason":"end_turn","content":[{"type":"text","text":"Done."}],"usage":{"output_tokens":40,"cache_read_input_tokens":9000}}}
{"type":"system","subtype":"turn_duration","uuid":"s1","timestamp":"2026-01-02T10:00:05.000Z","durationMs":5000}
{"type":"system","subtype":"compact_boundary","uuid":"s2","timestamp":"2026-01-02T10:05:00.000Z","compactMetadata":{"trigger":"manual","preTokens":542963,"postTokens":17999,"durationMs":108560}}
{"type":"user","uuid":"u2","isCompactSummary":true,"timestamp":"2026-01-02T10:05:00.500Z","message":{"role":"user","content":"This session is being continued from a previous conversation that ran out of context."}}
{"type":"user","uuid":"u3","isMeta":true,"timestamp":"2026-01-02T10:04:10.000Z","message":{"role":"user","content":"<local-command-caveat>Caveat: generated by a local command.</local-command-caveat>"}}
{"type":"user","uuid":"u4","timestamp":"2026-01-02T10:04:10.000Z","message":{"role":"user","content":"<command-name>/compact</command-name>"}}
{"type":"user","uuid":"u5","timestamp":"2026-01-02T10:12:00.000Z","message":{"role":"user","content":[{"type":"text","text":"the panel shows the wrong prompt"},{"type":"image","source":{"type":"base64","media_type":"image/png","data":"AAAA"}}]}}
{"type":"user","uuid":"u6","isMeta":true,"timestamp":"2026-01-02T10:12:00.000Z","message":{"role":"user","content":[{"type":"text","text":"[Image: source: /tmp/shot.png]"}]}}
{"type":"assistant","uuid":"a2","requestId":"r2","timestamp":"2026-01-02T10:12:06.000Z","effort":"high","message":{"model":"claude-opus-5","stop_reason":"tool_use","content":[{"type":"tool_use","id":"t1","name":"Read","input":{"file_path":"/x/record.go"}}],"usage":{"output_tokens":60,"cache_read_input_tokens":18000}}}
`

func TestCompactSummaryDoesNotOpenATurn(t *testing.T) {
	got := replay(t, compactSequence).Turn()
	if got == nil {
		t.Fatal("no turn built")
	}
	if strings.Contains(got.Prompt, "This session is being continued") {
		t.Fatalf("pinned the compact summary as the prompt: %q", got.Prompt)
	}
	if want := "the panel shows the wrong prompt"; got.Prompt != want {
		t.Errorf("Prompt = %q, want %q", got.Prompt, want)
	}
	// The turn must be timed from the real prompt, not from the compaction
	// eight minutes earlier.
	if got.Duration > time.Minute {
		t.Errorf("Duration = %v, want the span of the real turn only", got.Duration)
	}
}

func TestCompactBoundaryOpensTheNextTurn(t *testing.T) {
	rows := replay(t, compactSequence).Turn().Rows
	if len(rows) == 0 {
		t.Fatal("no rows")
	}
	c := rows[0].Change
	if c == nil {
		t.Fatalf("first row is not the compaction: %+v", rows[0])
	}
	for _, want := range []string{"COMPACT", "manual", "542k", "17k"} {
		if !strings.Contains(c.Label, want) {
			t.Errorf("label %q missing %q", c.Label, want)
		}
	}
	if n := countChanges(rows, "COMPACT"); n != 1 {
		t.Errorf("compaction appears %d times, want 1", n)
	}
}

// A change appended outside the request stream must survive rebuild, which
// replaces Rows wholesale on every record.
func TestPermissionModeChangeSurvivesRebuild(t *testing.T) {
	const lines = `
{"type":"user","uuid":"u1","timestamp":"2026-01-02T10:00:00.000Z","message":{"role":"user","content":"go"}}
{"type":"permission-mode","uuid":"p1","permissionMode":"default"}
{"type":"assistant","uuid":"a1","requestId":"r1","timestamp":"2026-01-02T10:00:04.000Z","message":{"model":"claude-opus-5","stop_reason":"tool_use","content":[{"type":"tool_use","id":"t1","name":"Bash","input":{"command":"ls"}}],"usage":{"output_tokens":10}}}
{"type":"permission-mode","uuid":"p2","permissionMode":"acceptEdits"}
{"type":"assistant","uuid":"a2","requestId":"r2","timestamp":"2026-01-02T10:00:09.000Z","message":{"model":"claude-opus-5","stop_reason":"end_turn","content":[{"type":"text","text":"done"}],"usage":{"output_tokens":12}}}
`
	rows := replay(t, lines).Turn().Rows
	if n := countChanges(rows, "MODE"); n != 1 {
		t.Fatalf("mode change appears %d times, want 1: %s", n, describeRows(rows))
	}
}

func countChanges(rows []Row, prefix string) int {
	n := 0
	for _, r := range rows {
		if r.Change != nil && strings.HasPrefix(r.Change.Label, prefix) {
			n++
		}
	}
	return n
}

func describeRows(rows []Row) string {
	var b strings.Builder
	for _, r := range rows {
		switch {
		case r.Change != nil:
			b.WriteString("[change " + r.Change.Label + "]")
		case r.Fork != nil:
			b.WriteString("[fork " + r.Fork.Skill + "]")
		case r.Action != nil:
			b.WriteString("[action " + r.Action.Tool + "]")
		}
	}
	return b.String()
}
